version: '3'
services:
  db:
    image: "postgres:12-alpine"
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: "haggle"
      POSTGRES_PASSWORD: "haggle"
      POSTGRES_DB: "haggle"
    volumes:
      - "db:/var/lib/postgresql/data"
volumes:
  db: