name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "haggle-de-haghag"
          heroku_email: "osak.63@gmail.com"
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          cd web
          npm install
          npm run build
      - uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          repository-name: haggle-de-haghag/haggle-de-haghag.github.io
          ssh-key: ${{ secrets.GH_PAGES_DEPLOY }}
          branch: master
          folder: web/dist