name: deploy
on: [workflow_dispatch]
jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          cd web
          npm install
          npm run build
      - uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          repository-name: haggle-de-haghag/haggle-de-haghag.github.io
          ssh-key: ${{ secrets.GH_PAGES_DEPLOY }}
          branch: master
          folder: web/dist